@extends('layouts.admin')

@section('content')
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan venenatis mi ac cursus. Donec semper arcu ut scelerisque vestibulum. Duis congue nisi in ante hendrerit dictum. Vestibulum ullamcorper lorem sollicitudin, aliquam enim eu, fringilla lorem. Phasellus egestas tortor tincidunt felis condimentum suscipit. Nulla lacus odio, condimentum quis libero ut, rutrum tempus sem. Curabitur rhoncus interdum laoreet. Nulla ac varius nunc. Duis dignissim neque sed mauris gravida, a ornare turpis feugiat. </p>
@endsection
